name: Staging Build

on:
  pull_request:
  types: [labeled]

jobs:
  build:
    if: github.event.label.name == 'build'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Upload artifact
      uses: actions/upload-artifact@v2-preview
      with: 
        name: apk
        path: app/build/outputs/apk/debug/*.apk
